name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'fragments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./fragments
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fragments:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fragments:${{ github.sha }}
